# Generated by Django 5.0.6 on 2024-06-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0002_sede_tipo_gimnasio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios_gym/sedes/'),
        ),
    ]
