# Generated by Django 5.0.6 on 2024-06-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0003_alter_sede_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
