# Generated by Django 5.0.6 on 2024-06-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0005_alter_sede_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='imagen',
        ),
    ]
