# Generated by Django 5.0.6 on 2024-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0007_sede_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('Telefono', models.CharField(max_length=100)),
                ('Mensaje', models.TextField(null='True')),
            ],
        ),
    ]
