# Generated by Django 5.0.6 on 2024-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0008_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Mensaje',
            field=models.TextField(null=True),
        ),
    ]
