# Generated by Django 5.0.6 on 2024-06-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0009_alter_usuarios_mensaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuarios_contactados',
        ),
    ]
