# Generated by Django 5.0.6 on 2024-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0011_usuarios_gimnasio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_gimnasio',
            name='Mensaje',
        ),
        migrations.AlterField(
            model_name='usuarios_gimnasio',
            name='Telefono',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
