# Generated by Django 5.0.6 on 2024-06-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_gym', '0012_remove_usuarios_gimnasio_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios_gimnasio',
            name='apellido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
